<a href="https://colab.research.google.com/github/Hassan-Ahlgamdi/python-notes/blob/main/notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# here where i save my python notes for ml and data science

# Python Basics

## Data Collectoin types


### Tuples


In [ ]:
"""
  - an orderd sequence of values
  - can containg diffrente data types and nested tuples
  - immutable
  - access the elements by it's indext
  - provide slicing
  - you can concatinate tuples
"""
tuple1 = (1,2,43,"Hello world!" , True, 3.14159)
print(tuple1[0])

tuple2  = (4  , 5 ," Hassan " , False)
concat_tuple = tuple1 + tuple2
print(concat_tuple)

tuple3 = (3,2,4,5,1,6,8,7)
sorted_tuple = sorted(tuple3)
print(sorted_tuple)

tuple4 = (1,2,3, tuple1  , ("one" , "two"))
print(tuple4[3][1])
print(tuple4[4][0])
print(len(concat_tuple))


1
(1, 2, 43, 'Hello world!', True, 3.14159, 4, 5, ' Hassan ', False)
[1, 2, 3, 4, 5, 6, 7, 8]
2
one


### Lists

In [ ]:
"""
 - orderd sequence of values
 - can containg diffrente data types and nested Lists and tuples
 - mutable
 - access the elements by it's indext
 - provide slicing
 - you can concatinate tuples => use list.extend([]) to add elements for the list
 - you can add one element => list.append([])
"""

list1 = [1,2,3,"hassan"]
print(list1)

# add one element at the end
list1.append("Hello, world!")
print(list1)

# delete an elment from the list
del(list1[-1])
print(list1)

# add mutiple elements using extend
list2 = [4,5,6]
list1.extend(list2)
print(list1)

# change an element
list1[3] = 0
print(list1)


[1, 2, 3, 'hassan']
[1, 2, 3, 'hassan', 'Hello, world!']
[1, 2, 3, 'hassan']
[1, 2, 3, 'hassan', 4, 5, 6]
[1, 2, 3, 0, 4, 5, 6]


### Dictionaries

In [ ]:
"""
 - type of collection in python
 - contain Keys and values
 - Keys are immutable and uniqe 'like indext in tuples and lists'
"""
DICT = {
    "Hassan" : 2004,
    "Ahmed baj" : 2003,
    "Mohhamed" : 2001
}

# access an element with its key
print(DICT["Hassan"])

# print all keys
print(DICT.keys())
# print all values
print(DICT.values())

# delete an element
del(DICT["Ahmed baj"])
print(DICT)

# check if the key exist
print("Hassan" in DICT)
print("Ahmed" in DICT)

# add element to the dictionary
DICT["Khaled"] = 1998
print(DICT)

print(list(DICT.keys()))

2004
dict_keys(['Hassan', 'Ahmed baj', 'Mohhamed'])
dict_values([2004, 2003, 2001])
{'Hassan': 2004, 'Mohhamed': 2001}
True
False
{'Hassan': 2004, 'Mohhamed': 2001, 'Khaled': 1998}
['Hassan', 'Mohhamed', 'Khaled']


### Sets

In [ ]:
"""
 - unorderd collection of objects 'no element is repeted'
 - add using => set.add()
 - remove using => set.remove()
"""

setA = {"Hassan" , "Khaled" , "bj"}
setB = {"bj", "sarah" , "amal"}
# intersection
print(setA & setB)
# union
print(setA.union(setB))
# check if set is subset
print(setA.issubset(setB))

{'bj'}
{'Khaled', 'sarah', 'amal', 'Hassan', 'bj'}
False


## Objects and Classes in python

#### access modifires for attributes and methods
x => public and its the default \
_x => protected \
__x => private

In [ ]:
class Employee:
  def __init__(self , name , salary):
    self.name = name
    self.__salary = salary
  def get_salary(self):
    return self.__salary
  def __private_method(self):
    print("This is private method, you can't use it out of the class")

emp1 = Employee("hassan", 100000)
print(emp1.name)
print(emp1.get_salary())
# print(emp1.__salary) # this code will not work
# emp1.private_method() # this code will not work

hassan
100000


### general informations about oop in python

In [ ]:
# this is how to creat a class
class Student :
  university_name = "KAU" # static member or class member
  # this is working as a constructor
  def __init__(self, name, age, id, gpa): # self work as this in java i think
    self.name = name
    self.age = age
    self.id = id
    self.gpa = gpa
  # every method should have 'self' as the first parameter in it, and it's refer to the object who is calling the method
  def talk(self):
    print(f"this is me {self.name} talking")

  def grades(self):
    print(f"my GPA is {self.gpa}")

  def whatIsSelf(self):
    print(self) # this will print the location of the object in the memory

In [ ]:
# how to creat an object
std1 = Student("Hassan Algamdi", 20 , "2335917", 4.98)
std1.talk()
std1.grades()
std1.whatIsSelf()

# python allow adding new attributes after object creation even if this attribute not in the class
std1.father = "Bander"
print(std1.father) # now the attribute 'father' stored in std1 object, but when you creat new another object it will not have this attribute in it
# delete 'father' attribute
del std1.father
# and you can delete an object
del std1

std2 = Student("sarah", 21 , '123', 5)
print(std2.university_name)

# dir(std1) # similar to 'toString'

this is me Hassan Algamdi talking
my GPA is 4.98
Bander
KAU


### Inheritance
- python allow multiple inheritance

#### super class

In [ ]:
class Vehicle:
  def __init__(self, company, owner, color, current_speed):
    self.company = company
    self.owner = owner
    self.color = color
    self.current_speed = current_speed

  def move(self):
    print("The vehicle has moved")
  def stop(self):
    print("Tha vehicle has stopped")

#### child classes

In [ ]:
class Car(Vehicle): # this is how to inherite a class
  def display(self):
    print("This is car class")
  def move(self): # override
    print("The car has moved")
  def stop(self): # override
    print("The car has stopped")

class Pike(Vehicle):
  def display(self):
    print("This is Pike class")
  def move(self): # override
    print("The pike has moved")
  def stop(self): # override
    print("The pike has stopped")

# this example to show how super() and constructor inheritance work
class Plane(Vehicle):
  def __init__(self, company, owner, color, current_speed, number_of_travles):
    super().__init__(company, owner, color, current_speed) # how to use super in python to call the parent constructor
    self.number_of_travles = number_of_travles

#### main method
there is no main method in python but to make it easier for me "java programmer"

In [ ]:
car1 = Car("Ford", "Bander", "Gold", 100)
pike1 = Pike("Mitsubishi", "Abdulrahman", "Black", 0)
car1.display()
car1.move()
pike1.display()
pike1.stop()

"""
MRO 'method resolution order' اتوقع
this is the method who is responsible of tracking the method calling in inheritenc classes
to use it Enter the name of the class. mro()
"""
print(Pike.mro())
p1 = Plane("Saudi planes" , "rich man" , "white", 0 , 5)


This is car class
The car has moved
This is Pike class
The pike has stopped
[<class '__main__.Pike'>, <class '__main__.Vehicle'>, <class 'object'>]


## Files in python





to open file in python we use the following mehtod

<pre>open("file Name", "mode")</pre>
mode: is what are we going to do with the file
- "r" => only read from the file "default value".
- "w" => read and write from the file, also can creat the file.
- "x" => creat the file
- "a" => append and write at the end of the file

#### "a" vs "w"
w: will delete everything in the file and write new things
a: will append and write the new lines at the end of the file

In [2]:
file = open("myfile.txt", "w") # to creat the file
file.write("Hello world!") # to write anything in the file
# print(file.read()) # read from the file
file.close() # cloes the file

In [12]:
file2 = open('combined_data.csv', 'r')
print(file2.read(10))
print(file2.tell()) # this will tell you where the corsour at , at what charachter
file2.seek(0) # this will move the corsour to the start of the file
print(file2.tell())
print(file2.readline())
print(file2.tell())
file2.close()

Name,Major
10
0
Name,Major,Year,GPA

21


#### try and catch exceptoins to close files

In [15]:
# you can do this method
try:
  file = open('combined_data.csv', 'r')
  print(file.write("Hello world!"))
except:
  print('somthing went wrong!!!')
finally:
  file.close()
file.closed

somthing went wrong!!!


True

In [25]:
# or open with 'with'
with open('combined_data.csv', 'r') as filex:
  print(filex.read(10))
# this will open the file inside the block of with and the file will close outside it
print(filex.closed)

Name,Major
True


# **مكتبات**

## Numpy

In [ ]:
import numpy as np

In [ ]:
A = np.array([1,2,3,4,5]) # 1D array
B = np.array([
              [1,0],
              [0,1]]) # 2D array
C = np.array([[
              [1,2,3],
              [4,5,6],
              [7,8,9]]]) # 3D array
# print(A.dtype , B.dtype , C.dtype) int 64
# print(A.ndim) 1
# print(B.ndim) 2
# print(C.ndim) 3
print(A.shape, B.shape , C.shape)
print(f"items in A = {A.size} , items in B = {B.size} , items in C = {C.size}")

(5,) (2, 2) (1, 3, 3)
items in A = 5 , items in B = 4 , items in C = 9


In [ ]:
x = np.array([2.5 , 6.2])
x.astype(int)

array([2, 6])

In [ ]:
s = np.array(['1' , '2' , '3'])
s.dtype

dtype('<U1')

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a = np.arange(4,9) # (start, stop , step)
a

array([4, 5, 6, 7, 8])

In [ ]:
np.linspace(1,10,10) #(start , stop'enclodid', how many elemtns in the arary)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
print(np.random.random((2,2)))
print("#" * 50)
print(np.random.randn(2,1))
print("#" * 50)
print(np.random.randint(1,100,(10,5)))

[[0.81566467 0.99181936]
 [0.42372711 0.23886006]]
##################################################
[[ 0.82431009]
 [-0.48268621]]
##################################################
[[73 30 30 95 48]
 [22 85 89 20 78]
 [93 88 82  3 77]
 [86 70 78 25 76]
 [68 85 91 97 65]
 [53 63 13 41 54]
 [73 90 32 12 47]
 [70 81  6 12 32]
 [96 75 70 97 97]
 [71 12 83  7 86]]


In [ ]:
print(np.full((2,2) , 11))
print("#" * 50)
print(np.full((4,4) , [1,2,3,4]))
print("#" * 50)
print(np.eye(4)) # identity matrix

[[11 11]
 [11 11]]
##################################################
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
##################################################
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
"""
 - shape manuplation :
when having an array with shape (12) you can reshape it to (3,4) or (4,3) or (6,2) or (2,6)
the size should equal to the first shape
size = every dimension * others
ex: shape(2,3,4) size => 2*3*4 = 24
to reshape an arrya use
nameOfTheArrya.reshape((size1,size2,...sizen))

 - to return the original shape use 'make it one dimension'
nameOfTheArrya.flatten() or nameOfTheArrya.ravel()

-  to make the rows columns and the columns row use 'transpose'
nameOfTheArrya.transpose()
"""
a = np.arange(1,13)
b = a.reshape((3,4))
print(b)
#print(a.reshape((3,3))) # this will cause an error
print(b.transpose())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
"""
Mathmatical operations between arrays
a + b or np.add(a,b)
a - b or np.subtract(a,b)
a * b or np.multiply(a,b)
a / b or np.divide(a,b)
a ** b or np.power(a,b
a % b or np.mod(a,b)
 'the arrays should be in the same shape to perfrom theses opereations'

 - matrics multiplication use 'np.dot()'
if the shape of matrics a is (x,4)
the shape of be should (4,y)
where x and y could be any number and the shape (x,y) is the result matrix
#################################
other usefull functions
np.sin(a)
np.cos(a)
np.tan(a)
np.exp(a)
np.log(a)
np.sqrt(a)
np.sum(a)
np.max(a)
np.min(a)
np.mean(a)
np.median(a)
np.std(a)
np.var(a)
"""
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
b = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])
np.dot(a,b) # or you can use a @ b

array([[ 50,  60],
       [114, 140]])

## pandas

In [ ]:
import pandas as pd

In [ ]:
lst = [1,2,3,4]
s = pd.Series(lst, dtype = float, index=["a",'b','c','d']) # you can change the data type using dtype / and change the index uding index ] ['a', 'b'...]
s

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [ ]:
x = pd.Series(["Hassa" , "Khaled"])
y = pd.Series(["Sarah", "Remm"])
z = pd.concat([x,y], ignore_index=True) # ignore_index will ignore the index in the original list and start new indexing for this series
print(z)
#.drop(index to delete) will return a series without the dropped elemment
# .copy will retrurn a copy of the series
s = pd.Series([1,2,3,4,4,4,3,3,3,5,5,5,6])
s.drop_duplicates(inplace=True) # inplace=True will change the original series
print(s)
# s.add(number) will add the number to every element of the series
# s.sub(number) same
# s.mul(number) *
# s.div(number) /

0     Hassa
1    Khaled
2     Sarah
3      Remm
dtype: object

In [ ]:
# Data Frames
data = {
    'department' : ['CS','IT','IS'],
    'number of students' : [90,88,78],
    'lowest grade': [90.1, 87.5,83.2]
}
df = pd.DataFrame(data)

#print(df)

df2 = pd.read_csv('file.csv')
new = ["Name", "Major", "Year","GPA"]
df2.columns = new
#df2.head(n) first 5 rows / or n rows if enterd
#df2.tail(n) last 5 rows / or n rows if enterd
#df2.describe() give you the count/mean/std/min/25%/50%/75%/max values
df2[['Major','GPA']].groupby('Major').mean()

GPA
Major      
CS     4.89
IS     5.00
IT     4.98

In [ ]:
# retrive data from the data frame
df3 = pd.read_csv('combined_data.csv')
df3['Name'] # return one column
df3[["Major",'GPA']] # return multiple columns
df3[5:11] # retrun rows from index 5 to index 10 / retrun rows will all columns
df3.loc[5:11, ["Major", "GPA"]] # return row form 5 to 11 / you should specify the columns
df3.sample(10) # return n number of random samples, random_state=x this will prevent the change in the sample
df3[df3["GPA"]>4.95] # using conditions with data frames
df3.isnull()
df3[df3["Name"].isnull()] # if True will return the row

Empty DataFrame
Columns: [Name, Major, Year, GPA]
Index: []

In [ ]:
# math operatoin and data manuplation
df3["GPA"].min() # max() , sum() , count() ...
def gpa_bounus(gpa):
  return gpa+0.15
df3["GPA"].apply(gpa_bounus) # apply a function to every element in the series , and to save the results write df3['GPA] = ....
df3.drop("Major", axis=1) # axis=1 for columns and axis=0 for rows , inplac=True will save the changes to the original data frame
#dropna() 'all' will delete if all the element in the axis(1 for columns, 0 for row) are null| 'any' will delete if one element or more is null
#fillna(n) replace null values with n
m = df3.sort_values(by="GPA", ascending=False) # inplace=True to save changes to the original data frame
df3[['Major', 'GPA']].groupby('Major').mean()

GPA
Major          
CS     4.785625
IS     4.768846
IT     4.806800
SE     4.722727